import 'normalize.css'
import './styles/variables.css'
import './styles/base.css'
import './styles/vt-backdrop.css'
import './styles/vt-doc-base.css'
import './styles/vt-doc-code.css'
import './styles/vt-doc-custom-blocks.css'
import './styles/vt-flyout.css'
import './styles/vt-hamburger.css'
import './styles/vt-link.css'
import './styles/vt-menu.css'
import './styles/vt-menu-group.css'
import './styles/vt-menu-link.css'
import './styles/vt-social-link.css'
import './styles/vt-social-links.css'
import './styles/vt-switch.css'
import './styles/vt-switch-appearance.css'
import './styles/vt-box.css'

export * from './types/menu'
export * from './types/socialLink'

export { default as VTIconAlignJustify } from './components/icons/VTIconAlignJustify.vue'
export { default as VTIconAlignLeft } from './components/icons/VTIconAlignLeft.vue'
export { default as VTIconAlignRight } from './components/icons/VTIconAlignRight.vue'
export { default as VTIconCommand } from './components/icons/VTIconCommand.vue'
export { default as VTIconChevronDown } from './components/icons/VTIconChevronDown.vue'
export { default as VTIconChevronLeft } from './components/icons/VTIconChevronLeft.vue'
export { default as VTIconChevronRight } from './components/icons/VTIconChevronRight.vue'
export { default as VTIconChevronUp } from './components/icons/VTIconChevronUp.vue'
export { default as VTIconDiscord } from './components/icons/VTIconDiscord.vue'
export { default as VTIconExternalLink } from './components/icons/VTIconExternalLink.vue'
export { default as VTIconFacebook } from './components/icons/VTIconFacebook.vue'
export { default as VTIconGitHub } from './components/icons/VTIconGitHub.vue'
export { default as VTIconLinkedIn } from './components/icons/VTIconLinkedIn.vue'
export { default as VTIconMoreHorizontal } from './components/icons/VTIconMoreHorizontal.vue'
export { default as VTIconMoon } from './components/icons/VTIconMoon.vue'
export { default as VTIconPlus } from './components/icons/VTIconPlus.vue'
export { default as VTIconSearch } from './components/icons/VTIconSearch.vue'
export { default as VTIconSlack } from './components/icons/VTIconSlack.vue'
export { default as VTIconSun } from './components/icons/VTIconSun.vue'
export { default as VTIconTwitter } from './components/icons/VTIconTwitter.vue'
export { default as VTIconLanguages } from './components/icons/VTIconLanguages.vue'

export { default as VTBackdrop } from './components/VTBackdrop.vue'
export { default as VTFlyout } from './components/VTFlyout.vue'
export { default as VTHamburger } from './components/VTHamburger.vue'
export { default as VTLink } from './components/VTLink.vue'
export { default as VTMenu } from './components/VTMenu.vue'
export { default as VTSocialLink } from './components/VTSocialLink.vue'
export { default as VTSocialLinks } from './components/VTSocialLinks.vue'
export { default as VTSwitch } from './components/VTSwitch.vue'
export { default as VTSwitchAppearance } from './components/VTSwitchAppearance.vue'
