import 'normalize.css'
import './styles/variables.css'
import './styles/base.css'

export * from './composables/appearance'
export * from './composables/menu'
export * from './composables/socialLink'

export { default as VTIconAlignJustify } from './components/icons/VTIconAlignJustify.vue'
export { default as VTIconAlignLeft } from './components/icons/VTIconAlignLeft.vue'
export { default as VTIconAlignRight } from './components/icons/VTIconAlignRight.vue'
export { default as VTIconCommand } from './components/icons/VTIconCommand.vue'
export { default as VTIconChevronDown } from './components/icons/VTIconChevronDown.vue'
export { default as VTIconChevronLeft } from './components/icons/VTIconChevronLeft.vue'
export { default as VTIconChevronRight } from './components/icons/VTIconChevronRight.vue'
export { default as VTIconChevronUp } from './components/icons/VTIconChevronUp.vue'
export { default as VTIconDiscord } from './components/icons/VTIconDiscord.vue'
export { default as VTIconExternalLink } from './components/icons/VTIconExternalLink.vue'
export { default as VTIconFacebook } from './components/icons/VTIconFacebook.vue'
export { default as VTIconGitHub } from './components/icons/VTIconGitHub.vue'
export { default as VTIconLinkedIn } from './components/icons/VTIconLinkedIn.vue'
export { default as VTIconMoreHorizontal } from './components/icons/VTIconMoreHorizontal.vue'
export { default as VTIconMoon } from './components/icons/VTIconMoon.vue'
export { default as VTIconPlus } from './components/icons/VTIconPlus.vue'
export { default as VTIconSearch } from './components/icons/VTIconSearch.vue'
export { default as VTIconSlack } from './components/icons/VTIconSlack.vue'
export { default as VTIconSun } from './components/icons/VTIconSun.vue'
export { default as VTIconTwitter } from './components/icons/VTIconTwitter.vue'

export { default as VTFlyout } from './components/VTFlyout.vue'
export { default as VTHamburger } from './components/VTHamburger.vue'
export { default as VTLink } from './components/VTLink.vue'
export { default as VTMenu } from './components/VTMenu.vue'
export { default as VTSocialLink } from './components/VTSocialLink.vue'
export { default as VTSocialLinks } from './components/VTSocialLinks.vue'
export { default as VTSwitchAppearance } from './components/VTSwitchAppearance.vue'
