import 'normalize.css'
import './styles/variables.css'
import './styles/base.css'

export * from './composables/appearance'
export * from './composables/socialLink'

export { default as VTIconDiscord } from './components/icons/VTIconDiscord.vue'
export { default as VTIconFacebook } from './components/icons/VTIconFacebook.vue'
export { default as VTIconGitHub } from './components/icons/VTIconGitHub.vue'
export { default as VTIconLinkedIn } from './components/icons/VTIconLinkedIn.vue'
export { default as VTIconMoon } from './components/icons/VTIconMoon.vue'
export { default as VTIconSearch } from './components/icons/VTIconSearch.vue'
export { default as VTIconSlack } from './components/icons/VTIconSlack.vue'
export { default as VTIconSun } from './components/icons/VTIconSun.vue'
export { default as VTIconTwitter } from './components/icons/VTIconTwitter.vue'

export { default as VTHamburger } from './components/VTHamburger.vue'
export { default as VTSocialLink } from './components/VTSocialLink.vue'
export { default as VTSocialLinks } from './components/VTSocialLinks.vue'
export { default as VTSwitchAppearance } from './components/VTSwitchAppearance.vue'
